### ISSUE TITLE
Please provide artisan command to clear & backup setting.json file

### ISSUE THREAD

**Issue by azulkipli** [thetispro/laravel5-setting#2]
Please provide artisan command to clear & backup setting.json file

**Comment by bke-daniel** [comment]
After a while I have to agree with that. It would be nice to have an option to get back to the default / initial settings.

**Comment by thetispro** [comment]
It's already quite easy. Backup (using php 'copy' or Laravel filesystem handler) the original setting file, then use the included features (different file name  and/or different path) to read the saved file.
