### ISSUE TITLE
Output options

### ISSUE THREAD

**Issue by robert83ft** [thetispro/laravel5-setting#3]
Hi there,

Is there any option to get pretty output? If I use Setting to set/write with 

`Setting::set('Spot',....`

My output looks like this

`{"Spot":"{\n    \"General\": {\n        \"temp_sms_treshold\": {\n            \"order\": 0,\n            \"name\": \"Temperature threshold\",\n            \"value\": 32\n        },\n        \"upl ...`

All in one line .. seems double-encoded as well. If I use Setting to read and I write with Laravel : 

`File::put(base_path() . '/config/config_encode.json', json_encode($data['settings'], JSON_PRETTY_PRINT));`

I can keep settings file like :

{
    "Spot": {
        "General": {
            "temp_sms_treshold": {
                "order": 0,
                "name": "Temperature threshold",
                "value": 32
            },
            "uploads_dir": {
                "order": 1,
                "name": "Upload folder",
                "value": "\/var\/www\/html\/main\/uploads\/"
            }

That's more readable. Am I missing something here? Am I doing something wrong?

Robert

**Comment by thetispro** [comment]
I'm using IDE's like PhpStorm or Netbeans : the output is always pretty.

**Comment by robert83ft** [comment]
Hi

I'm also using PHPStorm to code. My question had no relation to the IDE being used to write code.
It's the output of the code.

Please see the attached screenshot of the Setting::set (right) output vs File::put (left) ...

![output](https://cloud.githubusercontent.com/assets/7677543/11499102/5430adea-982c-11e5-8426-bfc475818584.jpg)

Regards,
Robert
