### ISSUE TITLE
Unable to access Setting::get() in config/app.php

### ISSUE THREAD

**Issue by tusharvikky** [thetispro/laravel5-setting#4]
Hello,

If we dump Setting::get(); in routes it works all fine. However, when we try to use these configs in config files published we are unable to do that. 
Throws:

```
Fatal error: Class 'Setting' not found in /Users/username/Sites/laravel/config/stream-laravel.php on line 15

```

**Comment by thetispro** [comment]
You have to import the full namespace

<?php
namespace xxxxxxxx;
use Thetispro\Setting\Setting;
 …
$mySetting=Setting::get(…);

OR

use  \ that will specify that the name is required from the global space even in the context of the namespace

$mySetting=\Setting::get(…);
