### ISSUE TITLE
Vendor:publish throws an exception

### ISSUE THREAD

**Issue by shomisha** [thetispro/laravel5-setting#7]
I can't complete the installation because it won't publish. It throws an ErrorException saying: Illegal offset type in unset

Here's the trace:
![stacktra](https://cloud.githubusercontent.com/assets/23019509/23526340/07d9afb8-ff92-11e6-9823-872bc000b85f.PNG)

**Comment by thetispro** [comment]
Version of Laravel  ?

For >= 5.4 please give me a few days for updating this repo.

**Comment by shomisha** [comment]
Yeah, I'm using 5.4. Ok, thanks for the help :)

**Comment by thetispro** [comment]
Update your composer.json to  v. 1.1

"thetispro/laravel5-setting": "1.1"

**Comment by shomisha** [comment]
It won't pull the package, says it only exists as [dev-master] and that it isn't loaded because of my constraint to 1.1

**Comment by thetispro** [comment]
Thanks. Use:

"thetispro/laravel5-setting": "1.1.x-dev"
